"""init

Revision ID: e06b753e4daa
Revises: 7a867e33bb9e
Create Date: 2025-07-11 13:56:50.570367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06b753e4daa'
down_revision: Union[str, Sequence[str], None] = '7a867e33bb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'created_at_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at_test', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('materials', 'created_at')
    # ### end Alembic commands ###
